### ISSUE TITLE
Add other file types

### ISSUE THREAD

**Issue by smit1678** [openimagerynetwork/oin-metadata-spec#11]
Right now we're defining the standard for file types to be geotiff. There has been some interest in allowing additional file types like jpeg and jp2. For example, [Sentinel](http://sentinel-pds.s3-website.eu-central-1.amazonaws.com/) data is stored as `.jp2` or some UAV imagery sharing has used jp2 for easy transfer. Example Sentinel imagery: http://sentinel-s2-l1c.s3.amazonaws.com/tiles/10/R/FV/2016/2/12/0/B02.jp2

One advantage would be the ability to have compressed file types stored within nodes resulting in lower storage costs and faster transfer. But compression increases computing needed to process these file types. 

@cgiovando @lossyrob @mojodna Is there room to support additional file types like jpeg and jp2? Are there concerns or considerations we need to discuss before we say these are accepted? 

For jp2, one consideration is that it [is not compiled by default](http://www.gdal.org/formats_list.html).

**Comment by sethfitz** [comment]
(I'm approaching this from the tiling angle. From a pure file-sharing standpoint, sure.)

I still like GeoTIFFs more, as they facilitate partial reads (which dramatically increase effective transfer speeds) through internal tiling (though the files do need to be set up that way). If lossy compression is desired (lossless compression is available using LZW and DEFLATE), content can be JPEG-encoded.

A quick read of the GDAL docs suggests that JP2s can also be tiled (and have something called "precincts" which may obviate tiling to some extent). However, there appear to be multiple drivers (some non-free) and they're generally less well-understood by the masses (e.g., me).

The chunking process could probably be adapted to support other formats (and might even work out of the box, actually...), though I don't know at what performance cost (if any).

As I mentioned IRL, it may make more sense to adapt the ingestion process instead. Right now (as I understand it), it directly copies data from the source URL and drops it in S3. Instead, it could/should rewrite images using our preferred compression / internal tiling / etc. and convert to GeoTIFF from some set of supported formats.

My sense is that if we can assume certain truths about the images being tiled we can optimize accordingly.

**Comment by jflasher** [comment]
Jumping in since @smit1678 mentioned the Sentinel data. While it is provided in JP2, I don't think I've met too many people who think that's a good thing. It just provides extra overhead when used next to other formats.

This could also be a distinction between OIN and OAM. Maybe it's fine to have whatever on OIN, but if I'm building tooling against the OAM API, it'd be nice to not have to worry about what file format the underlying data is in. Probably easier for downstream usage if that decisions is made by the platform itself.

**Comment by smit1678** [comment]
Thanks @jflasher and great point @mojodna. Seems like maybe it's more worthwhile getting the Upload process to not just be a pass-through but file type converter. Accept a JP2 but then convert to a geotiff. Agreed that it would then be a good way to optimize processes after that.

**Comment by smit1678** [comment]
To follow up here, OAM incorporated new JP2 file type conversion into geotiff + compression in https://github.com/hotosm/oam-uploader-api/pull/41. Closing this convo since there was agreement to stay focused on geotiff.
